# Generated by Django 2.2.2 on 2019-06-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('address_from', models.TextField()),
                ('address_to', models.TextField()),
                ('rate', models.FloatField()),
                ('distance', models.FloatField()),
                ('pickup_date', models.DateField()),
                ('weight', models.FloatField()),
                ('cargo_type', models.TextField()),
                ('cargo_count', models.FloatField()),
                ('price', models.FloatField()),
                ('map', models.TextField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
