# Generated by Django 2.2.2 on 2019-06-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='car_type',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
