# Generated by Django 2.2.2 on 2019-06-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_auto_20190627_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='url',
        ),
    ]
