# Generated by Django 2.2.2 on 2019-06-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0006_auto_20190627_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='logist',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
