# Generated by Django 2.2.2 on 2019-07-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0008_bid_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vat',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
